[tool.poetry]
name = "rps_game"
version = "0.0.1"
description = "Rock, Paper, Scissors game"
authors = ["Massimiliano Botticelli <massimiliano.botticelli@gmail.com"]


[tool.poetry.dependencies]
python = "^3.11"