game:
  rules: "SPOCK_LIZARD"    # Options: "BASIC_RULES", "SPOCK_LIZARD"
  mode: "best_of"         # Options: "first_to", "best_of"
  target_score: 10          # Used if mode is "first_to"
  rounds: 10                # Used if mode is "best_of"

players:
  player_one:
    type: "LLMPlayer" # Options: "HumanPlayer", "ComputerPlayer"
    name: "Gemini"
  player_two:
    type: "ComputerPlayer" # Options: "HumanPlayer", "ComputerPlayer"
    name: "Computer A"
